import type { AssessmentPaper } from '@vedaai/shared-types';
import { SectionBlock } from './SectionBlock';
import { GraduationCap, Clock } from 'lucide-react';

interface ExamPaperProps {
  paper: AssessmentPaper;
  totalMarks?: number;
  dueDate?: string;
}

export function ExamPaper({ paper, totalMarks, dueDate }: ExamPaperProps) {
  let startNumber = 1;
  const totalQ = paper.sections.reduce((acc, s) => acc + s.questions.length, 0);

  return (
    <article className="exam-paper animate-fade-in-up">
      {/* Paper Header */}
      <header className="mb-8 border-b border-slate-200 pb-8 text-center">
        {/* Institution badge */}
        <div className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-50 px-4 py-1.5 text-xs font-semibold text-slate-500 uppercase tracking-widest mb-6">
          <GraduationCap className="h-3.5 w-3.5" />
          VedaAI Assessment
        </div>

        <h1 className="text-2xl font-bold text-slate-900 md:text-3xl uppercase tracking-wide leading-tight">
          {paper.title}
        </h1>

        {/* Meta row */}
        <div className="mt-4 flex flex-wrap items-center justify-center gap-4 text-sm text-slate-500">
          {totalMarks && (
            <span className="flex items-center gap-1.5">
              <span className="h-1.5 w-1.5 rounded-full bg-purple-500" />
              Total Marks: <strong className="text-slate-700 ml-1">{totalMarks}</strong>
            </span>
          )}
          {dueDate && (
            <span className="flex items-center gap-1.5">
              <Clock className="h-3.5 w-3.5" />
              {dueDate}
            </span>
          )}
          <span className="flex items-center gap-1.5">
            <span className="h-1.5 w-1.5 rounded-full bg-indigo-500" />
            Questions: <strong className="text-slate-700 ml-1">{totalQ}</strong>
          </span>
        </div>

        {/* Student fields */}
        <div className="mt-8 grid grid-cols-3 gap-6 text-left">
          {['Name', 'Roll Number', 'Section'].map((label) => (
            <div key={label} className="space-y-1">
              <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">{label}</span>
              <div className="border-b-2 border-slate-300 pb-1 pt-4" />
            </div>
          ))}
        </div>

        {/* Instructions */}
        <div className="mt-6 rounded-xl bg-slate-50 border border-slate-200 px-5 py-4 text-left">
          <p className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">General Instructions</p>
          <ul className="space-y-1 text-xs text-slate-600">
            <li>• All questions are compulsory unless stated otherwise.</li>
            <li>• Write legibly and clearly in the answer booklet.</li>
            <li>• Marks are indicated against each question.</li>
          </ul>
        </div>
      </header>

      {/* Sections */}
      {paper.sections.map((section) => {
        const block = (
          <SectionBlock key={section.title} section={section} startNumber={startNumber} />
        );
        startNumber += section.questions.length;
        return block;
      })}

      {/* Footer */}
      <footer className="mt-10 border-t border-slate-200 pt-6 text-center text-xs text-slate-400">
        Generated by VedaAI · AI-Powered Assessment Creator
      </footer>
    </article>
  );
}
